[project]
name = "ds-core"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "jupyter-ai>=3.0.1",
    "jupyterlab>=4.5.0",
    "matplotlib>=3.10.7",
    "numpy>=2.3.5",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "polars>=1.35.2",
    "psycopg2-binary>=2.9.11",
    "pyarrow>=22.0.0",
    "python-dotenv>=1.2.2",
    "scipy>=1.18.0",
    "seaborn>=0.13.2",
    "sqlalchemy>=2.0.48",
    "xlsxwriter>=3.2.9",
]
